### ISSUE TITLE
Need to fix all these issues

### ISSUE THREAD

**Issue by nhathuy13598** [dat-dv/30days#17]
I have set up CI but it doesn't work now because of warning when building. Please fix all issues listed in CodeFactor: [Stype](https://www.codefactor.io/repository/github/v-dat/30days/issues?category=Style#), [Maintainability ](https://www.codefactor.io/repository/github/v-dat/30days/issues?category=Maintainability)

**Comment by V-Dat** [comment]
this issues is dupplicated with #9 #5 #19

**Comment by V-Dat** [comment]
> this issues is dupplicated with #9 #5 #19 in PR-3 and PR-9-1

**Comment by dat-dv** [comment]
this issues is dupplicated with #9 #5  #19  in PR-3 and PR-9-1
